name: update tool
on:
  schedule:
    - cron: "0 0 * * Mon"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download 
        run: |
          wget https://github.com/bromite/bromite/releases/latest/download/ruleset_converter
          
      - name: Generate date 
        run: echo "DATE=$(date +%F)" >> $GITHUB_ENV
        
      - name: Commit tool 
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'ruleset_converter'
          default_author: github_actor 
          message: 'Cập nhật tool: ${{ env.DATE }}'
          push: true
          
